// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNAD__9X1NOatdc2bD200AxOs21rW7BYk',
    appId: '1:803804560312:web:b0485f9ab64125c9d2ad4d',
    messagingSenderId: '803804560312',
    projectId: 'chat-app-d7ca7',
    authDomain: 'chat-app-d7ca7.firebaseapp.com',
    storageBucket: 'chat-app-d7ca7.appspot.com',
    measurementId: 'G-TVE943CKDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC73g7Hi4wwQYukzVt4acEBkj339nz_h-8',
    appId: '1:803804560312:android:7c61b07e97ae6ef3d2ad4d',
    messagingSenderId: '803804560312',
    projectId: 'chat-app-d7ca7',
    storageBucket: 'chat-app-d7ca7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvqLExfkZyYPuw0xu7EJH4NKYJgI7pxg',
    appId: '1:803804560312:ios:67886db105619672d2ad4d',
    messagingSenderId: '803804560312',
    projectId: 'chat-app-d7ca7',
    storageBucket: 'chat-app-d7ca7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvqLExfkZyYPuw0xu7EJH4NKYJgI7pxg',
    appId: '1:803804560312:ios:67886db105619672d2ad4d',
    messagingSenderId: '803804560312',
    projectId: 'chat-app-d7ca7',
    storageBucket: 'chat-app-d7ca7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNAD__9X1NOatdc2bD200AxOs21rW7BYk',
    appId: '1:803804560312:web:c106a42e8c7040f6d2ad4d',
    messagingSenderId: '803804560312',
    projectId: 'chat-app-d7ca7',
    authDomain: 'chat-app-d7ca7.firebaseapp.com',
    storageBucket: 'chat-app-d7ca7.appspot.com',
    measurementId: 'G-P0EH1V2NRB',
  );
}
